AllCops:
  Exclude:
    - vendor/**/*
    - spec/dummy/**/*
    - bin/**/*

Metrics/LineLength:
  Exclude:
    - activejob-scheduler.gemspec

Metrics/MethodLength:
  Exclude:
    - lib/active_job/scheduler/event.rb
